"""
Legal PDF Report Generator - Creates official-looking evidence reports for cybercrime reporting.
"""

import os
from datetime import datetime
from typing import Dict, Any

def generate_evidence_pdf(incident_data: Dict[str, Any]) -> bytes:
    """
    Generates a PDF report containing evidence.
    For this implementation, we return a structured text/html representation
    that can be converted to PDF on the fly or used as a placeholder.
    """
    # In a real environment, use ReportLab or FPDF
    # Here we create a professional text report as a starting point

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_id = f"EP-{datetime.now().strftime('%Y%m%d')}-{os.urandom(2).hex().upper()}"

    report = f"""
    ============================================================
                     EPROHORI CYBERCRIME REPORT
    ============================================================
    REPORT ID: {report_id}
    GENERATED: {timestamp}
    STATUS: VERIFIED EVIDENCE

    ------------------------------------------------------------
    1. INCIDENT SUMMARY
    ------------------------------------------------------------
    Type: {incident_data.get('type', 'Unknown')}
    Description: {incident_data.get('description', 'No description provided')}
    Detected Confidence: {incident_data.get('confidence', 0)*100:.1f}%

    ------------------------------------------------------------
    2. TECHNICAL EVIDENCE
    ------------------------------------------------------------
    Source Content: {incident_data.get('content', 'N/A')}
    Detected Indicators:
    {chr(10).join([' - ' + i for i in incident_data.get('indicators', [])])}

    ------------------------------------------------------------
    3. LEGAL RECOMMENDATIONS
    ------------------------------------------------------------
    Based on the Digital Security Act (Bangladesh), it is recommended
    to report this incident to:
    - BTRC Cyber Crime Department
    - Police Cyber Support for Women (if applicable)
    - CID Cyber Crime Investigation Center

    Steps:
    1. Do not delete the original message/email.
    2. Do not pay any money requested.
    3. File a GD at your local police station with this Report ID.

    ------------------------------------------------------------
    This report was generated by EProhori AI Engine.
    For verification, visit: https://eprohori.tech/verify/{report_id}
    ============================================================
    """

    return report.encode('utf-8')
